In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [3]:
from google.colab import files
uploaded = files.upload()
occupancy = pd.read_csv('occupancy.csv')

Saving occupancy.csv to occupancy.csv

In [4]:
occupancy.isnull().sum()

timestamp    0
102          0
105          0
107          0
108          0
            ..
1167         0
1168         0
1170         0
1172         0
1173         0
Length: 248, dtype: int64

In [5]:
occupancy.head(2)

,timestamp,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,12,16,24,15,6,8,24,1,2,...,0,12,1,38,26,162,10,1,8,15
1,2,12,16,24,15,6,8,24,1,2,...,0,12,1,38,26,162,10,1,8,15

occupancy.csv stores station occupancy/load over time.

Rows = timestamps
Columns = station IDs

Used for:
- congestion analysis
- utilization forecasting
- pricing triggers

In [6]:
from google.colab import files
uploaded = files.upload()
duration = pd.read_csv('duration.csv')
duration.head(2)

Saving duration.csv to duration.csv

,timestamp,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,0.49,0.871111,0.98,0.762222,0.326667,0.381111,0.98,0.054444,0.108889,...,0.0,0.326667,0.054444,1.905556,1.306667,8.493333,0.544444,0.054444,0.435556,0.326667
1,2,0.75,1.333333,1.50,1.166667,0.500000,0.583333,1.50,0.083333,0.166667,...,0.0,0.500000,0.083333,2.916667,2.000000,13.000000,0.833333,0.083333,0.666667,0.500000

In [7]:
duration.isnull().sum()

timestamp    0
102          0
105          0
107          0
108          0
            ..
1167         0
1168         0
1170         0
1172         0
1173         0
Length: 248, dtype: int64

duration.csv stores charging duration metrics over time.

Used for:
- charger occupation analysis
- congestion behavior

In [8]:
from google.colab import files
uploaded = files.upload()
volume = pd.read_csv('volume.csv')
volume.head(2)

Saving volume.csv to volume.csv

,timestamp,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,2.858333,5.907222,6.478889,5.145,2.286667,3.048889,5.526111,0.381111,0.762222,...,0.0,2.286667,0.381111,12.195556,8.956111,240.236111,5.335556,0.381111,2.286667,2.096111
1,2,4.375000,9.041667,9.916667,7.875,3.500000,4.666667,8.458333,0.583333,1.166667,...,0.0,3.500000,0.583333,18.666667,13.708333,367.708333,8.166667,0.583333,3.500000,3.208333

In [9]:
volume.isnull().sum()

timestamp    0
102          0
105          0
107          0
108          0
            ..
1167         0
1168         0
1170         0
1172         0
1173         0
Length: 248, dtype: int64

volume.csv stores charging demand/energy volume.

Used for:
- demand forecasting
- revenue estimation

In [10]:
from google.colab import files
uploaded = files.upload()
price = pd.read_csv('price.csv')
price.head(2)

Saving price.csv to price.csv

,timestamp,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,1,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,...,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425
1,2,0.924,1.124167,0.926364,0.99,1.004,1.015,1.111818,1.15,0.543333,...,0.69,0.905,0.7,0.956875,1.04,0.753185,0.906667,1.2,1.038,1.0425

In [11]:
price.isnull().sum()

timestamp    0
102          0
105          0
107          0
108          0
            ..
1167         0
1168         0
1170         0
1172         0
1173         0
Length: 248, dtype: int64

price.csv stores tariff/pricing values over time.

Used for:
- dynamic pricing analysis
- revenue optimization

In [12]:
from google.colab import files
uploaded = files.upload()
information = pd.read_csv('information.csv')
information.head(2)

Saving information.csv to information.csv

,num,grid,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,1,102,30,3,27,0.71,114.1030,22.54041,0,0
1,3,105,93,0,93,0.77,114.1208,22.55127,0,0

In [13]:
information.isnull().sum()

num                0
grid               0
count              0
fast_count         0
slow_count         0
area               0
lon                0
la                 0
CBD                0
dynamic_pricing    0
dtype: int64

information.csv stores operational metadata:
- CBD
- dynamic pricing
- charger types
- station properties

In [14]:
from google.colab import files
uploaded = files.upload()
stations = pd.read_csv('stations.csv')
stations.head(2)

Saving stations.csv to stations.csv

   station_id   latitude   longitude  fast  slow  count
0           1  22.716272  113.826349     5     5     10
1           2  22.678851  114.049721    20     0     20

In [15]:
stations.isnull().sum()

station_id    0
latitude      0
longitude     0
fast          0
slow          0
count         0
dtype: int64

stations.csv stores physical infrastructure data:
- charger counts
- geographic coordinates

In [16]:
from google.colab import files
uploaded = files.upload()
time = pd.read_csv('time.csv')
time.head(2)

Saving time.csv to time.csv

   month  day  year  hour  minute  second
0      6   19  2022     0       0       0
1      6   19  2022     0       5       0

In [17]:
time.isnull().sum()

month     0
day       0
year      0
hour      0
minute    0
second    0
dtype: int64

time.csv maps timestamps to real datetime values.

5-minute interval data.

In [18]:
from google.colab import files
uploaded = files.upload()
adj = pd.read_csv('adj.csv')
adj.head(2)

Saving adj.csv to adj.csv

,node_id,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,102,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,105,0,1,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
adj.isnull().sum()

node_id    0
102        0
105        0
107        0
108        0
          ..
1167       0
1168       0
1170       0
1172       0
1173       0
Length: 248, dtype: int64

adj.csv stores connectivity relationships between stations.

In [20]:
from google.colab import files
uploaded = files.upload()
distance = pd.read_csv('distance.csv')
distance.head(2)

Saving distance.csv to distance.csv

,Unnamed: 0,102,105,107,108,109,110,111,115,123,...,1160,1162,1163,1164,1166,1167,1168,1170,1172,1173
0,0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0.0,0.0,1.216116,1.142223,0.0,0.0,1.563217,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
distance.isnull().sum()

Unnamed: 0    0
102           0
105           0
107           0
108           0
             ..
1167          0
1168          0
1170          0
1172          0
1173          0
Length: 248, dtype: int64

distance.csv stores pairwise distances between stations.

In [22]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_excel('acndata_sessions.json.xlsx')

print(df.head())

Saving acndata_sessions.json.xlsx to acndata_sessions.json.xlsx
   _meta  end  min_kWh     site  start  _items                       _id  \
0    NaN  NaN      NaN  caltech    NaN     NaN  5bc90cb9f9af8b0d7fe77cd2
1    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd3
2    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd4
3    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd5
4    NaN  NaN      NaN      NaN    NaN     NaN  5bc90cb9f9af8b0d7fe77cd6

   clusterID                 connectionTime                 disconnectTime  \
0       39.0  Wed, 25 Apr 2018 11:08:04 GMT  Wed, 25 Apr 2018 13:20:10 GMT
1       39.0  Wed, 25 Apr 2018 13:45:10 GMT  Thu, 26 Apr 2018 00:56:16 GMT
2       39.0  Wed, 25 Apr 2018 13:45:50 GMT  Wed, 25 Apr 2018 23:04:45 GMT
3       39.0  Wed, 25 Apr 2018 14:37:06 GMT  Wed, 25 Apr 2018 23:55:34 GMT
4       39.0  Wed, 25 Apr 2018 14:40:34 GMT  Wed, 25 Apr 2018 23:03:12 GMT

   ... userID  userInputs WhPerMile  kWhRequested milesRequested  \
0  ...    NaN         NaN       NaN           NaN            NaN
1  ...    NaN         NaN       NaN           NaN            NaN
2  ...    NaN         NaN       NaN           NaN            NaN
3  ...    NaN         NaN       NaN           NaN            NaN
4  ...    NaN         NaN       NaN           NaN            NaN

  minutesAvailable modifiedAt  paymentRequired  requestedDeparture  userID.1
0              NaN        NaN              NaN                 NaN       NaN
1              NaN        NaN              NaN                 NaN       NaN
2              NaN        NaN              NaN                 NaN       NaN
3              NaN        NaN              NaN                 NaN       NaN
4              NaN        NaN              NaN                 NaN       NaN

[5 rows x 27 columns]

acndata_sessions.json stores raw charging session records.

In [23]:
occupancy_long = occupancy.melt(
    id_vars='timestamp',
    var_name='station_id',
    value_name='occupancy'
)
occupancy_long.head()

   timestamp station_id  occupancy
0          1        102         12
1          2        102         12
2          3        102         12
3          4        102         12
4          5        102         12

In [24]:
occupancy_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2134080 entries, 0 to 2134079
Data columns (total 3 columns):
 #   Column      Dtype
---  ------      -----
 0   timestamp   int64
 1   station_id  object
 2   occupancy   int64
dtypes: int64(2), object(1)
memory usage: 48.8+ MB

In [25]:
duration_long = duration.melt(
    id_vars='timestamp',
    var_name='station_id',
    value_name='duration'
)

In [26]:
volume_long = volume.melt(
    id_vars='timestamp',
    var_name='station_id',
    value_name='volume'
)

In [27]:
price_long = price.melt(
    id_vars='timestamp',
    var_name='station_id',
    value_name='price'
)

In [28]:
occupancy_long['station_id'] = occupancy_long['station_id'].astype(int)
duration_long['station_id'] = duration_long['station_id'].astype(int)
volume_long['station_id'] = volume_long['station_id'].astype(int)
price_long['station_id'] = price_long['station_id'].astype(int)

In [29]:
time['datetime'] = pd.to_datetime(time[['year','month','day','hour','minute','second']])
time.head()

   month  day  year  hour  minute  second            datetime
0      6   19  2022     0       0       0 2022-06-19 00:00:00
1      6   19  2022     0       5       0 2022-06-19 00:05:00
2      6   19  2022     0      10       0 2022-06-19 00:10:00
3      6   19  2022     0      15       0 2022-06-19 00:15:00
4      6   19  2022     0      20       0 2022-06-19 00:20:00

In [30]:
time['timestamp'] = range(1, len(time)+1)
time = time[['timestamp','datetime']]

In [31]:
master_df = occupancy_long.merge(
    duration_long,
    on=['timestamp','station_id']
)

In [32]:
master_df = master_df.merge(
    volume_long,
    on=['timestamp','station_id']
)

In [33]:
master_df = master_df.merge(
    price_long,
    on=['timestamp','station_id']
)

In [34]:
master_df = master_df.merge(
    time,
    on='timestamp'
)

In [35]:
information = information.rename(columns={'grid':'station_id'})

In [36]:
master_df = master_df.merge(
    information,
    on='station_id',
    how='left'
)

In [37]:
master_df.head()

,timestamp,station_id,occupancy,duration,volume,price,datetime,num,count,fast_count,slow_count,area,lon,la,CBD,dynamic_pricing
0,1,102,12,0.49,2.858333,0.924,2022-06-19 00:00:00,1,30,3,27,0.71,114.103,22.54041,0,0
1,2,102,12,0.75,4.375000,0.924,2022-06-19 00:05:00,1,30,3,27,0.71,114.103,22.54041,0,0
2,3,102,12,0.75,4.375000,0.924,2022-06-19 00:10:00,1,30,3,27,0.71,114.103,22.54041,0,0
3,4,102,12,0.75,4.375000,0.924,2022-06-19 00:15:00,1,30,3,27,0.71,114.103,22.54041,0,0
4,5,102,12,0.75,4.375000,0.924,2022-06-19 00:20:00,1,30,3,27,0.71,114.103,22.54041,0,0

In [38]:
master_df.shape

(2134080, 16)

In [39]:
master_df.isnull().sum()

timestamp          0
station_id         0
occupancy          0
duration           0
volume             0
price              0
datetime           0
num                0
count              0
fast_count         0
slow_count         0
area               0
lon                0
la                 0
CBD                0
dynamic_pricing    0
dtype: int64

In [40]:
master_df.to_csv('master_dataset.csv', index=False)